// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8MvnPg4P4if_ElQhBhaJPb9PgLXULbQI',
    appId: '1:480657283506:web:d61f05a594fb658b592cab',
    messagingSenderId: '480657283506',
    projectId: 'phone-otp-3e416',
    authDomain: 'phone-otp-3e416.firebaseapp.com',
    storageBucket: 'phone-otp-3e416.appspot.com',
    measurementId: 'G-QKX0V8L77Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEuPgNBiVXOpV2sSbMrA_JxGHfTfvzmVA',
    appId: '1:480657283506:android:67f69a9f34b15c2e592cab',
    messagingSenderId: '480657283506',
    projectId: 'phone-otp-3e416',
    storageBucket: 'phone-otp-3e416.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5pZTVuVvf8eiwcOZCvyt7mSq7eDtb7l8',
    appId: '1:480657283506:ios:97462c13d3b11ba7592cab',
    messagingSenderId: '480657283506',
    projectId: 'phone-otp-3e416',
    storageBucket: 'phone-otp-3e416.appspot.com',
    iosClientId: '480657283506-fd1lg1ehmhu6pm9c4thujnquu5c6g0l6.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneOtpSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5pZTVuVvf8eiwcOZCvyt7mSq7eDtb7l8',
    appId: '1:480657283506:ios:97462c13d3b11ba7592cab',
    messagingSenderId: '480657283506',
    projectId: 'phone-otp-3e416',
    storageBucket: 'phone-otp-3e416.appspot.com',
    iosClientId: '480657283506-fd1lg1ehmhu6pm9c4thujnquu5c6g0l6.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneOtpSignup',
  );
}
